[package]
name = "solana-job-queue"
version = "0.1.0"
description = "On-chain multi-tenant job queue — a Web2 backend pattern rebuilt on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solana_job_queue"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.32.1"
